### ISSUE TITLE
[stable/fluentd-elasticsearch] Cannot download image

### ISSUE THREAD

**Issue by naseemkullah** [kiwigrid/helm-charts#113]
Hello,

I am getting:
`Back-off pulling image "gcr.io/fluentd-elasticsearch/fluentd:v2.5.2"`

also https://console.cloud.google.com/gcr/images/fluentd-elasticsearch/GLOBAL/fluentd seems to not have any public images. 

I was wondering if anyone else was experiencing this?

**Comment by 3nin6** [comment]
also seen here https://github.com/kubernetes/kubernetes/issues/78684

**Comment by naseemkullah** [comment]
At the time of writing this the repo is public again but the most recent tag seems to be `v2.4.0`

**Comment by monotek** [comment]
Thanks for the hint. We're on int but can take a while.

For the time being i've build the image again and pushed it to
monotek/fluentd-elasticsearch:27

build log: https://travis-ci.org/monotek/fluentd-elasticsearch/jobs/541612466

**Comment by monotek** [comment]
Should work again

**Comment by volatilemolotov** [comment]
@monotek looks like happened again with 2.6.0

**Comment by monotek** [comment]
update to newest chart version please or edit image manualy to: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L2
