### ISSUE TITLE
Skipped value (map[]) for 'extraConfigMaps', as it is not a table

### ISSUE THREAD

**Issue by zaikinlv** [kiwigrid/helm-charts#122]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
HELM: 2.12.2,2.14.1
Kubernetes: 1.13.5

**Which chart in which version**:
3.0.1

**What happened**:
kiwigrid/fluentd-elasticsearch chart produces warnings (see. how to reproduce it) when used as a subchart. 

**What you expected to happen**:
No warnings

**How to reproduce it** (as minimally and precisely as possible):
1. Create simplistic parent chart / specify fluentd-elasticsearch in requirements.yaml
2. Override `extraConfigMaps` in values.yaml of parent chart

**parent-chart/values.yaml:**
```
fluentd-elasticsearch:
  configMaps:
    useDefaults:
      outputConf: false
  extraConfigMaps:
    output.conf: |-
      <match **>
        @id elasticsearch
        @type elasticsearch
        @log_level info
         .....
```
3. run `helm template parent-chart > out.yaml`:
```
Warning: Building values map for chart 'fluentd-elasticsearch'. Skipped value (map[]) for 'extraConfigMaps', as it is not a table
Warning: Building values map for chart 'fluentd-elasticsearch'. Skipped value (map[]) for 'extraConfigMaps', as it is not a table
Warning: Building values map for chart 'fluentd-elasticsearch'. Skipped value (map[]) for 'extraConfigMaps', as it is not a table
Warning: Building values map for chart 'fluentd-elasticsearch'. Skipped value (map[]) for 'extraConfigMaps', as it is not a table
.
.
```
**Anything else we need to know**:
Commenting out `extraConfigMaps` in values.yaml (kiwigrid/fluentd-elasticsearch) or setting it equal to `{}` helps

**Comment by a7i** [comment]
Any ideas on this issue?

**Comment by harshitmahapatra** [comment]
I too faced the exact same issue!

**Comment by monotek** [comment]
No.
We also try to avoid umbrella charts. To much hassle to maintain...
