### ISSUE TITLE
Not able to connect to Amazon Elasticsearch Service

### ISSUE THREAD

**Issue by hirannair** [kiwigrid/helm-charts#124]
Hi there,

Im trying to send the logs from my kubernetes cluster to Amazon Elasticsearch Service.Unfortunately im getting an error. Below are the logs

$ kubectl logs es-fluentd-elasticsearch-5p2sb -c es-fluentd-elasticsearch             
2019-06-20 03:07:40 +0000 [error]: unexpected error error_class=NoMethodError error="undefined method `[]' for nil:NilClass"
  2019-06-20 03:07:40 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:324:in `detect_es_major_version'
  2019-06-20 03:07:40 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:250:in `block in configure'
  2019-06-20 03:07:40 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/elasticsearch_index_template.rb:35:in `retry_operate'
  2019-06-20 03:07:40 +0000 [error]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:249:in `configure'

$ kubectl describe po/es-fluentd-elasticsearch-5p2sb
Name:               es-fluentd-elasticsearch-5p2sb
Namespace:          logging
Priority:           0
PriorityClassName:  <none>
Node:               aks-nodepool1
Start Time:         Wed, 19 Jun 2019 19:01:55 +1200
Labels:             app.kubernetes.io/instance=es
                    app.kubernetes.io/managed-by=Tiller
                    app.kubernetes.io/name=fluentd-elasticsearch
Annotations:        checksum/config: 83a245c2df3e2121122
                    scheduler.alpha.kubernetes.io/critical-pod: 
Status:             Running
IP:                 10.244.7.88
Controlled By:      DaemonSet/es-fluentd-elasticsearch
Containers:
  es-fluentd-elasticsearch:
    Container ID:   docker://b43d76073a8c2e52c55e8b8f205c77cf83d03eb10dd552a1ede9dd3ca200139e
    Image:          gcr.io/fluentd-elasticsearch/fluentd:v2.5.2
    Image ID:       docker-pullable://gcr.io/fluentd-elasticsearch/fluentd@sha256:6977aef7bad7ad590376a3d245473230ad1793a715b852360d058d6333913383
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 20 Jun 2019 15:07:13 +1200
      Finished:     Thu, 20 Jun 2019 15:07:40 +1200
    Ready:          False
    Restart Count:  220
    Liveness:       exec [/bin/sh -c LIVENESS_THRESHOLD_SECONDS=${LIVENESS_THRESHOLD_SECONDS:-300}; STUCK_THRESHOLD_SECONDS=${STUCK_THRESHOLD_SECONDS:-900}; if [ ! -e /var/log/fluentd-buffers ]; then
  exit 1;
fi; touch -d "${STUCK_THRESHOLD_SECONDS} seconds ago" /tmp/marker-stuck; if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-stuck -print -quit)" ]; then
  rm -rf /var/log/fluentd-buffers;
  exit 1;
fi; touch -d "${LIVENESS_THRESHOLD_SECONDS} seconds ago" /tmp/marker-liveness; if [ -z "$(find /var/log/fluentd-buffers -type d -newer /tmp/marker-liveness -print -quit)" ]; then
  exit 1;
fi;
] delay=600s timeout=1s period=60s #success=1 #failure=3
    Environment:
      FLUENTD_ARGS:               --no-supervisor -q
      OUTPUT_HOST:                localhost
      OUTPUT_PORT:                8080
      LOGSTASH_PREFIX:            logstash
      OUTPUT_SCHEME:              http
      OUTPUT_SSL_VERIFY:          true
      OUTPUT_SSL_VERSION:         TLSv1_2
      OUTPUT_BUFFER_CHUNK_LIMIT:  2M
      OUTPUT_BUFFER_QUEUE_LIMIT:  8
      K8S_NODE_NAME:               (v1:spec.nodeName)
    Mounts:
      /etc/fluent/config.d from config-volume (rw)
      /usr/lib64 from libsystemddir (ro)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from es-fluentd-elasticsearch-token-gg7kx (ro)
  es-fluentd-elasticsearch-aws-es-proxy:
    Container ID:  docker://1940858aab2125c0a86350afcff5175540e7abb92d19bc0a35ef979cc7849819
    Image:         abutaha/aws-es-proxy:0.9
    Image ID:      docker-pullable://abutaha/aws-es-proxy@sha256:c45e94d79848394cf5425eaa66408d0bd619d5aba25d00a2f3bc1da4b52c0da6
    Port:          <none>
    Host Port:     <none>
    Args:
      -endpoint
      https://search-kubernetes-logs-xxxxxxxxxxxxxxxxxxxx.ap-southeast-2.es.amazonaws.com:443
      -listen
      127.0.0.1:8080
    State:          Running
      Started:      Wed, 19 Jun 2019 19:02:03 +1200
    Ready:          True
    Restart Count:  0
    Environment:
      PORT_NUM:               443
      AWS_ACCESS_KEY_ID:      AKPPPPPPPPPPPPPPPPPP
      AWS_SECRET_ACCESS_KEY:  xccxcvxvcxxxxxxxxxxxx
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from es-fluentd-elasticsearch-token-gg7kx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:  
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:  
  libsystemddir:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/lib64
    HostPathType:  
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      es-fluentd-elasticsearch
    Optional:  false
  es-fluentd-elasticsearch-token-gg7kx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  es-fluentd-elasticsearch-token-gg7kx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason   Age                    From                                        Message
  ----     ------   ----                   ----                                        -------
  Warning  BackOff  7m8s (x4642 over 20h)  kubelet, aks-nodepool1-11121221  Back-off restarting failed container
  Normal   Pulled   2m14s (x221 over 20h)  kubelet, aks-nodepool1-11121221  Container image "gcr.io/fluentd-elasticsearch/fluentd:v2.5.2" already present on machine

Any help would be greatly appreciated

**Comment by monotek** [comment]
Ignored issue template. Closing...
