### ISSUE TITLE
[fluentd-elasticseach] - fluentd image Dockerfile

### ISSUE THREAD

**Issue by volatilemolotov** [kiwigrid/helm-charts#126]
<!-- Thanks for filing an issue!

**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
request for info 

Can annyone tell me where to find the Dockerfile for the image used. Who does maintain the image and is there a git repo for that. Thanks

**Comment by monotek** [comment]
I'm one of the maintainers. 

It can be found in the Kubernetes repo:
https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

**Comment by volatilemolotov** [comment]
Sorry i wasn't aware that the text doesnt show. Thanks for the info
