### ISSUE TITLE
json log is not picked up

### ISSUE THREAD

**Issue by zhenyulin** [kiwigrid/helm-charts#140]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm v2.14.1
Kubernetes GKE-1.10

**Which chart in which version**:
kiwigrid/helm-charts/fluentd-elasticsearch

**What happened**:
after the chart is deployed, logs are picked up in general to Elastic-search, available in Kibana; however only syslog, or text log in stdout are collected, json log is not picked up or parsed correctly.

**What you expected to happen**:
json log to be available in Kibana as well

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by jerbob92** [comment]
I also had this issue. I noticed it does work when you add the logstash fields to the output. I use Go and I use the following plugin to make my logger output the correct format: 
github.com/bshuster-repo/logrus-logstash-hook

It adds the fields `@version`, `type`, `@timestamp` and `message`. Using that plugin the messages show up fine.

**Comment by zhenyulin** [comment]
@simonklb not sure if the following is the correct way to add the extra configuration: 

```
extraConfigMaps:
  containers.input.conf: |-
    <filter kubernetes.**>
      @id filter_parser
      @type parser
      key_name log
      reserve_data true
      reserve_time true
      remove_key_name_field true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>
```

it seems log pickup is completely off when added this

**Comment by zhenyulin** [comment]
omitting timestamp in the log output is fixing the problem

**Comment by jerbob92** [comment]
Ah, that's why my fix works. It's because it changes the default `time` field of the json log output to `@timestamp`.

**Comment by ath88** [comment]
I had the same problem using (bunyan)[https://github.com/trentm/node-bunyan] as a logging framework for Node.js. Adding `reserve_time true` fixed the problem, and logs started flowing to ES.

**Comment by magicalbanana** [comment]
How do you add `reserve_time true` to the config with this chart?
