### ISSUE TITLE
[stable/fluentd-elasticsearch] Add a way to configure HTTP user/ password when using elasticsearch

### ISSUE THREAD

**Issue by gajus** [kiwigrid/helm-charts#15]
**Version of Helm and Kubernetes**:

N/A

**Which chart**:

stable/fluentd-elasticsearch

ES cluster might be protected with HTTP user/ password.

**Comment by monotek** [comment]
This should already be possible by adding it to the host var: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L27

It should look like this: 

```
elasticsearch:
  host: 'username:passowrd@elasticsearchhost'
```
