### ISSUE TITLE
Does this use the Posgres or sqlite backend for graphite?

### ISSUE THREAD

**Issue by mattdornfeld** [kiwigrid/helm-charts#166]
Is it capable of horizontally scaling or does it use the sqlite backend?

**Comment by monotek** [comment]
Graphite uses wisper database. 
See: https://graphite.readthedocs.io/en/latest/whisper.html

**Comment by mattdornfeld** [comment]
What about for the web app? The docs make it seem like if the default
SQLite is used than the service can’t be horizontally scaled?
https://graphite.readthedocs.io/en/latest/config-database-setup.html

**Comment by monotek** [comment]
Why would you want to scale the web frontend when the whisper database does not support that anyway?
Graphite chart uses a statefulset for a reason ;-)

**Comment by mattdornfeld** [comment]
Hmm maybe I’m a little confused. My understanding is that the web app,
whisper db, and carbon are all hosted in a single container (which in the
case of this helm chart is managed by the statefulset) I understand that
any time series metrics are stored in the whisper db. But according to the
docs

>The following configures the Django database settings. Graphite uses the
database for storing user profiles, dashboards, and for the Events
functionality. Graphite uses an SQLite database file...

So if my understanding is correct then if your horizontally scale the
statefulset every webapp will have its own SQLite file. So if I go to the 0
instance of the statefulset and add some dashboard and events configuration
that configuration info will not be available in the 1 instance of the
statefulset. The docs also say

>If running multiple Graphite-web instances, a database such as PostgreSQL
or MySQL is required so that all instances may share the same data source.

So that’s the motivation for my question. Does that make sense or am I
missing something?

Thanks,
Matt

**Comment by monotek** [comment]
You can't scale whisper db horizontal. 

I doubt there is need to scale the webapp at all. Most people I know don't even use the webapp so I guess you won't reach the amount of users at the same time in the webapp which would need you to scale the webapp up.
