### ISSUE TITLE
REQUEST: Add grok plugin

### ISSUE THREAD

**Issue by y0zg** [kiwigrid/helm-charts#170]
**FEATURE REQUEST**:
Please add grok plugin into fluentd dockerfile 

`gem "fluent-plugin-grok-parser", "~> 2.5.0"`

Reference:
https://github.com/fluent/fluentd-kubernetes-daemonset/commit/c44451b8982f0d36e9d1da7ac1c3a405c8609936

**Which chart in which version**:
```
apiVersion: v1
appVersion: 2.7.0
```

**Update:** I finally found Dockerfile for fluentd-elastic helm chart, so this is optional now https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image

**Comment by monotek** [comment]
fixed with: https://github.com/kiwigrid/helm-charts/commit/b10c635da0a6c4142b830a70171802fc899211eb
