### ISSUE TITLE
Path customisation changes from PR #99 were reverted in #101

### ISSUE THREAD

**Issue by kgeorga** [kiwigrid/helm-charts#190]
Hello,

PR #99 introduced a useful feature where it allowed to customise the paths mounted from the host. This is useful in our case where we are running Fluentd on Windows and the docker container logs are in `C:\ProgramData\docker\containers`.

on PR #101 the `volumeMounts` `mountPath` was reverted to a hardcoded one instead of being aligned with `hostPath` which takes it's value from the corresponding `hostLogDir` value. I am not sure what is the reasoning behind this but this makes it less flexible to accommodate custom setups.

It would also be helpful to add additional hostPaths to mount as for example in our case the kubelet logs are in C:\k (I guess this should be raised as a feature request).

**Comment by monotek** [comment]
Would be nice you could add an pr which fixes it :-)

**Comment by kgeorga** [comment]
hey @monotek I actually forked the repo and started on a PR that align hostPath with mountPath. Just wanted to understand the reasoning behind reverting PR #99 before I submit that. I could definitely add the extra host paths as part of this PR as well
