### ISSUE TITLE
[fluentd-elasticsearch] Suggestion: Make awsSigningSidecar port configurable

### ISSUE THREAD

**Issue by chadlwilson** [kiwigrid/helm-charts#196]
**FEATURE REQUEST**

When using the `awsSigningSidecar`; it'd be convenient if the **default** port was `9200` (rather than `8080`). This would make it consistent with the [default host/port of the fluent-elasticsearch plugin](https://docs.fluentd.org/output/elasticsearch#port-optional). This would avoid additional coupling of configuration between the fluentd config and the Helm chart config. (convention-over-configuration, if you will)

Alternatively; allowing this port to be **configurable** in the Helm chart would allow people to keep the port configuration self-contained within the Helm charts alone e.g via

```
awsSigningSidecar:
  enabled: true
  localPort: 9200
  # blah
```

Happy to submit a small PR if there is interest in taking this on and a name can be agreed upon for the value override.

**Comment by monotek** [comment]
Good idea to make it configurable :-)
But please keep current default to make it a non breaking change.

**Comment by chadlwilson** [comment]
Thanks @monotek - sure. How do you feel about the name to give the port variable?

**Comment by monotek** [comment]
port? :D

**Comment by Alien2150** [comment]
You need a PR for this one? @monotek

**Comment by chadlwilson** [comment]
Yeesh, I forgot about this. Was meaning to create one.

**Comment by Alien2150** [comment]
@chadlwilson i can quickly create one.

**Comment by Alien2150** [comment]
https://github.com/kiwigrid/helm-charts/pull/220/

**Comment by chadlwilson** [comment]
Thanks @Alien2150!
