### ISSUE TITLE
Unable to retrieve pull secret default/artifactory-docker-secret errors

### ISSUE THREAD

**Issue by julian-berks** [kiwigrid/helm-charts#232]
**Is this a request for help?**: Yes

---
This chart is working well and my logs appear to be passing to ES perfectly. 

But the logs on the fluentd pods are filling up with 
Nov 26 12:07:44 ip-10-8-10-126 kubelet: W1126 12:07:44.833517    3683 kubelet_pods.go:842] Unable to retrieve pull secret default/artifactory-docker-secret for default/qliksense-edge-auth-565cffd699-5wp7w due to secrets "artifactory-docker-secret" not found.  The image pull may not succeed.
Nov 26 12:07:46 ip-10-8-10-126 kubelet: W1126 12:07:46.833610    3683 kubelet_pods.go:842] Unable to retrieve pull secret default/artifactory-docker-secret for default/qliksense-dcaas-7bc47964d4-4rkjl due to secrets "artifactory-docker-secret" not found.  The image pull may not succeed.

There is no "artifactory-docker-secret" in my build and whatever it's trying to do doesn't appear to be needed. 

How do I stop this message?

Thanks.

**Comment by monotek** [comment]
closing, as issue template was ignored.
not an issue of the chart anyway.  
just configure your cluster properly.
