### ISSUE TITLE
Fluentd logs filling with messages

### ISSUE THREAD

**Issue by julian-berks** [kiwigrid/helm-charts#233]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Neither - -probably my fault but no idea what it's trying to do and can find no other forum to get assistance.

**Version of Helm and Kubernetes**:
Helm - v2.14.1
Kubernetes 1.13

**Which chart in which version**:
fluentd-elasticsearch-5.1.3	2.7.0         	default

**What happened**:
All works very well - application pod logs are getting to ES but the Fluentd logs are filling up with the following messages

Nov 27 07:59:35 ip-10-8-10-89 kubelet: W1127 07:59:35.523009    3534 kubelet_pods.go:842] Unable to retrieve pull secret default/artifactory-docker-secret for default/qliksense-encryption-567d4cf8d5-xl7rk due to secrets "artifactory-docker-secret" not found.  The image pull may not succeed.
Nov 27 07:59:39 ip-10-8-10-89 kubelet: W1127 07:59:39.526792    3534 kubelet_pods.go:842] Unable to retrieve pull secret default/artifactory-docker-secret for default/qliksense-dcaas-web-7c9fb776d-8dfmb due to secrets "artifactory-docker-secret" not found.  The image pull may not succeed.

**What you expected to happen**:
Pod Logs to be quiet

**How to reproduce it** (as minimally and precisely as possible):
install and run normally

**Anything else we need to know**:
I am a relatively new to kubernetes. 
The cluster works perfectly well and does what I require of it, as does this component so I am not aware of any issues or misconfiguration in my cluster. 
I have no idea what the error is referring to but clearly whatever it is trying to do is unnecessary in my particular case. How do I stop these messages from filling the logs and crashing the pods? 
Do I need to enable or add something to the cluster?
If there is a better forum to ask this I will be happy to swap over to it but I've not found it.

**Comment by monotek** [comment]
default/artifactory-docker-secret is not part of fluentd-elasticsearch. 

Seems you've configured a default registry secret, which is not available.

See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account
