### ISSUE TITLE
kiwigrid-ci-bot not working as intended

### ISSUE THREAD

**Issue by deitrix** [kiwigrid/helm-charts#27]
**What happened**:
Unable to add the kiwigrid repository. using command:
`helm repo add kiwigrid https://kiwigrid.github.io`.

Results in the following error:
`Error: Looks like "https://kiwigrid.github.io" is not a valid chart repository or cannot be reached: Failed to fetch https://kiwigrid.github.io/index.yaml : 404 Not Found`

**What you expected to happen**:
Repo to be added to helm

**How to reproduce it** (as minimally and precisely as possible):
`helm repo add kiwigrid https://kiwigrid.github.io`

**Anything else we need to know**:
It appears as though this is an issue with the new `kiwigrid-ci-bot`. A commit was made 30 minutes ago to the `kiwigrid/kiwigrid.github.io` github repository to remove the `index.yaml`. Commit reference: `2b56bcc`

**Comment by axdotl** [comment]
We reverted the latest change to get the repo working again.

We're now going to figure out the root cause. Until it's fixed, no new chart version will become available.

**Comment by axdotl** [comment]
Build fixed.
