### ISSUE TITLE
Please provide ability to configure Hawkbit after deployment

### ISSUE THREAD

**Issue by fabian-schlegel** [kiwigrid/helm-charts#270]
**Is this a request for help?**:

No, this is a short novel story about a mighty update server and his sidekick walking into a bar.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Which chart in which version**:

https://github.com/kiwigrid/helm-charts/tree/master/charts/hawkbit-update-server

**Detailed request**:

Please provide the ability to configure Hawkbit after deployment, so e.g. software module types can be added. This can easily be achieved by using the management API in a side car or job.

**Comment by monotek** [comment]
Developing a sidecar is not part of the chart. So imho wrong place to ask.

By the way the chart is on the way to deprecation so i guess we wont add any new functionality here.

Chart will move to eclipse/packages repo.
See: https://github.com/eclipse/packages/pull/18

After its moved, add your feature request there.
