### ISSUE TITLE
https://kiwigrid.github.io is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by aespejel** [kiwigrid/helm-charts#28]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
helm version
Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

**Which chart**:

**What happened**:
helm repo add kiwigrid https://kiwigrid.github.io
Error: Looks like "https://kiwigrid.github.io" is not a valid chart repository or cannot be reached: Failed to fetch https://kiwigrid.github.io/index.yaml : 404 Not Found

**What you expected to happen**:
Being able to add the repo

**How to reproduce it** (as minimally and precisely as possible):
helm repo add kiwigrid https://kiwigrid.github.io

**Anything else we need to know**:

**Comment by axdotl** [comment]
See #27
