### ISSUE TITLE
log_es_400_reason and request_timeout are not accepted config

### ISSUE THREAD

**Issue by gadelkareem** [kiwigrid/helm-charts#281]
**Is this a request for help?**:
No
---

**How to reproduce it** (as minimally and precisely as possible):
add this config to 
```
<match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      @log_level debug
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
      request_timeout 15s
      log_es_400_reason true
    </match>
```
the log will warn about there params log_es_400_reason and request_timeout. And the <match> will be ignored

**Comment by monotek** [comment]
Could you provide a pr for this please which makes it possible to enable this by values.yaml?

**Comment by gadelkareem** [comment]
I meant add the two params to https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml#L148 would produce a warning.

**Comment by bauer01** [comment]
@gadelkareem it's wrong section...you should place `log_es_400_reason true` in **output.conf.**

For example here https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml#L515 ;-)
