### ISSUE TITLE
which version of kubernetes fluentd plugin

### ISSUE THREAD

**Issue by ryandawsonuk** [kiwigrid/helm-charts#292]
I'm trying to find which version of the kubernetes plugin this fluentd configuration is using. Apologies for the question - it may look very simple but I'm not currently seeing the answer. 

Am looking into it as I want to use float time timestamps with nanosecond precision and for this [the plugin needs to be using the newer API](https://github.com/fluent/fluentd/issues/461)

**Comment by monotek** [comment]
The image is build from this file: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile

So currently Fluentd 1.8.0 is used.
