### ISSUE TITLE
[fluentd-elasticsearch] Migrating pos_file location change from helm/stable repo?

### ISSUE THREAD

**Issue by Ghazgkull** [kiwigrid/helm-charts#313]
I have a fluentd-elasticsearch deployment which was originally created from the old helm/stable chart. In that chart, the pos_file location in the containers.input.conf was `/var/log/fluentd-containers.log.pos`. In this new chart, the container.input.conf uses `/var/log/containers.log.pos` instead.

I am currently using this new chart, but with a completely overridden containers.input.conf solely for the purpose of maintaining our pos_file.

This change should affect almost all users of the old helm/stable chart. Can you provide any guidance on how to handle the migration? Or maybe just help customers like me understand what the consequences will be if we move to the new location and do nothing?

This would be great info to capture in the upgrade section of the readme and I'd be happy to contribute some prose if I knew the answers myself. :-)

**Comment by monotek** [comment]
I guess this would need a manual step. 
Backup pos file and add it to the new deployment.
