### ISSUE TITLE
Install-chart CI checks failing with helm v3.x

### ISSUE THREAD

**Issue by muffix** [kiwigrid/helm-charts#318]
**Is this a request for help?**:
No

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

**Version of Helm and Kubernetes**:
Helm `v3.x`
chart-testing-action `@master`

**Which chart in which version**:
N/A

**What happened**:
The install-chart Github checks are currently failing with the fllowing error message: 
`Error: invalid argument "1200" for "--timeout" flag: time: missing unit in duration 1200` (ex.: https://github.com/kiwigrid/helm-charts/pull/317/checks?check_run_id=536820725#step:5:120)

The CI setup currently passes a timeout value of `1200`, but helm expects a unit with it, e.g. `1200s`. This is expected behaviour [since Helm v3.x](https://github.com/helm/helm/issues/7375). 

The `chart-testing-action` is using `quay.io/helmpack/chart-testing:v3.0.0-beta.2` to run the checks since [this PR](https://github.com/helm/chart-testing-action/pull/22) was merged (see https://github.com/kiwigrid/helm-charts/pull/317/checks?check_run_id=536820725#step:5:7). Support for helm 2 has been moved to a branch: https://github.com/helm/chart-testing-action#chart-testing-action

**What you expected to happen**:
The install-chart step installs working charts correctly.

**How to reproduce it** (as minimally and precisely as possible):
Raise any PR that tries to install a helm chart

**Anything else we need to know**:
I'm going to open a PR to use the branch of `chart-testing-action` which supports helm 2 and uses  `quay.io/helmpack/chart-testing:v2.4.0` as before.

**Comment by monotek** [comment]
fixed with: https://github.com/kiwigrid/helm-charts/commit/f4e5dbad111bc3470fbebd2bc12a47470b3ec273
