### ISSUE TITLE
Found some warning after that no logs on fluent-elasticsearch

### ISSUE THREAD

**Issue by luckyr14** [kiwigrid/helm-charts#320]
/usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call                                           /usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:61: warning: The called method `initialize_client' is defined here                                                                                /usr/local/bundle/gems/fluentd-1.9.2/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call          /usr/local/bundle/gems/fluentd-1.9.2/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
--

**Comment by monotek** [comment]
github issue template ignored. closing.
