### ISSUE TITLE
Pushing to Harbor which requires a ca cert

### ISSUE THREAD

**Issue by MiellyEllen** [kiwigrid/helm-charts#325]
**Is this a request for help?**:
YES
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST
To push images to the Harbor (https://goharbor.io/) image registry  a ca cert is required for authentication. Is there any chance of adding that option to this plugin? Is there another mvn plugin that accomplishes this?

**Comment by monotek** [comment]
Please use the issue template. 
Its not clear about what chart you're talking about.

**Comment by MiellyEllen** [comment]
Sorry, submitted issue to incorrect repository. will delete
