### ISSUE TITLE
[fluentd-elasticsearch] Allow multiple hosts in config

### ISSUE THREAD

**Issue by samuel-begin** [kiwigrid/helm-charts#330]
FEATURE REQUEST

Since Fluentd config [accepts multiple hosts](https://docs.fluentd.org/output/elasticsearch#hosts-optional) in its config, I would like to be able to provide them through the chart.

So migrating the parameter:
Parameter | Description | Default
-- | -- | --
elasticsearch.host | Elasticsearch Host | elasticsearch-client

to:
Parameter | Description | Default
-- | -- | --
elasticsearch.hosts[] | Elasticsearch Hosts list | []

**Comment by samuel-begin** [comment]
I'll be working on this, since we need it for our deployment

Would you prefer to deprecate `host` and have migration doc? or you'd rather stay backwards compatible and have both parameters `host` and `hosts[]`?

**Comment by monotek** [comment]
I would prefer to deprecate host and have migration doc.
