### ISSUE TITLE
[fluentd-elasticsearch] - plugin-kubernetes_metadata_filter bug

### ISSUE THREAD

**Issue by Ghazgkull** [kiwigrid/helm-charts#340]
**Is this a request for help?**:
No

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
Helm 3.0.3 and Kubernetes 1.15

**Which chart in which version**:
8.0.1 and 9.0

**What happened**:
The 3.0.1 image of fluentd_elasticsearch used by this Helm chart is using a version of the `fluent-plugin-kubernetes_metadata_filter` plugin which contains a defect that affects customers as reported here:

https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/226

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
I think it would be a good idea to roll this helm chart back to using version 3.0.0 of fluentd_elasticsearch until they put out a version which picks up a fix.

Here's the commit in question (from March 24, 2020), which picked up the apparently bad version of the plugin:
https://github.com/kubernetes/kubernetes/commit/335bfe091131ea1024351095d8437772d02ff2d6#diff-832b8c3b755123d25adaca7ba80025dd

**Comment by monotek** [comment]
Lets wait for a fix in the lib. I'll create a new image versiobn if its ready.
In  the meanwhile you can just set another image tag in the values file.

**Comment by monotek** [comment]
@Ghazgkull 

I've build a new image, which contains plugin version 2.4.6. 
Please test with: monotek/fluentd-elasticsearch:latest

If it works i'll update the original quay.io image too and release also a new chart version.

**Comment by monotek** [comment]
should be fixed with: https://github.com/kiwigrid/helm-charts/pull/364
