### ISSUE TITLE
[fluentd-elasticsearch] Exclude specific pods from log collection

### ISSUE THREAD

**Issue by rgarcia89** [kiwigrid/helm-charts#341]
**FEATURE REQUEST:**

Is it somehow possible to exclude specific pods from log collection? I am especially thinking about the fluentd pods. They are producing tons of logs. Or only collect the stderr logs.

**Which chart in which version**:
fluentd-elasticsearch-8.0.1

**Comment by ChrisCooney** [comment]
👍 Would love to see this!

**Comment by monotek** [comment]
What about: https://docs.fluentd.org/filter/record_transformer#remove_keys

**Comment by rgarcia89** [comment]
This looks to me more like to filter out a key. However, what about filtering out for example all pods that have a label set `logging=false`. I have found the following fragment that excludes an entire namespace, which is also nice to save. But not what I was looking for
```
<match kubernetes.var.log.containers.**_kube-system_**>
  @type null
</match>
```
