### ISSUE TITLE
[fluentd-elasticsearch]: Support for forwarder-only mode

### ISSUE THREAD

**Issue by krezovic** [kiwigrid/helm-charts#345]
---

**FEATURE REQUEST** 

I'd like to use fluentd chart as a forwarder only which receives data from several fluent-bit instances installed on each node, perform parse, format and finally forward the data to elastic search.

The current chart makes this impossible. I'd be willing to do the work, should you agree to support this use-case.

**Comment by monotek** [comment]
I don't think this chart should become an all purpose tool.

Maybe your request is better off at: https://github.com/helm/charts/tree/master/stable/fluentd
