### ISSUE TITLE
[fluentd-elasticsearch] Why add plugins feature is gone ?

### ISSUE THREAD

**Issue by esteban1983cl** [kiwigrid/helm-charts#349]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:
Helm
```
❯ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```

Kubernetes
```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T12:36:28Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-879c36", GitCommit:"879c3621692a32b5d77a951ca0e61ee55aefc80f", GitTreeState:"clean", BuildDate:"2020-02-21T18:09:01Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
```
**Which chart in which version**:
9.0.0

**What happened**:
In 6.1.1 version I had the ability that add's fluentd-plugins but in this version I can't
I need install newrelic-fluentd plugin

**What you expected to happen**:
By chart values file I need the ability to add plugins.

**How to reproduce it** (as minimally and precisely as possible):
N/A

**Anything else we need to know**:
Nothing else to say thanks by this wonderful k8s-app

**Comment by monotek** [comment]
The current used fluentd docker imag has no build tools installed, so installation is not possible anymore.

see also: https://github.com/kiwigrid/helm-charts/issues/326
