### ISSUE TITLE
[fluentd-elasticsearch] integration with OpenDistro. Unable to debug further

### ISSUE THREAD

**Issue by anishnagaraj** [kiwigrid/helm-charts#351]
This is for a help

**What happened**:

I am using the fluentd-elasticsearch latest chart. I have successfully installed ElasticSearch and Kibana with OpenDistro on my AKS(Azure k8s service) cluster. 

But I am struggling to establish a connection between the Fluentd pods and the elastic search instance. I just get the following error:

`Could not communicate to Elasticsearch, resetting connection and trying again. end of file reached (EOFError)`

**What Iam expected to happen**:

The log level I have set is debug. But beyond the error I mentioned I unable to see more relevant errors or exceptions which can give me a clue of what is going wrong. What could I do to find the root cause of the problem?

**Anything else we need to know**:

However, when I make a curl call from the fluentd pod to Elastic search client I get a successful response back.

```
curl https://{es-svc-name}:9200/_cluster/health -u 'admin:admin' -k
{"cluster_name":"elasticsearch","status":"yellow","timed_out":false,"number_of_nodes":3,"number_of_data_nodes":1,"active_primary_shards":19,"active_shards":19,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":16,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":54.285714285714285}
```

**Comment by monotek** [comment]
not an aws user but have you set: https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L19
