### ISSUE TITLE
How to add 'pod status' as field using fluentd daemon while pushing logs to Elasticsearch

### ISSUE THREAD

**Issue by sushantc20** [kiwigrid/helm-charts#357]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

**Which chart in which version**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by monotek** [comment]
not possible.
