### ISSUE TITLE
Filter out fluentd logs

### ISSUE THREAD

**Issue by jopfeffe** [kiwigrid/helm-charts#367]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**: 3.2.4 + K8S 1.17

**Which chart in which version**: fluentd-elasticsearch 9.3.2

**What happened**: Fluentd Logs are shipped to elastic search. 

**What you expected to happen**: At least there should be a configuration option to disable this behavior.

``` 
<match kubernetes.var.log.containers.{{ include "fluentd-elasticsearch.fullname" . }}**.log>
      @type null
</match>
```

Kind regards
Jochen

**Comment by monotek** [comment]
you already can do this: 

https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/values.yaml#L236-L250

**Comment by jopfeffe** [comment]
I know that I can replace the entire config. But I thought it's a little bit overkill for this common config.

**Comment by monotek** [comment]
pr welcome ;-)
