### ISSUE TITLE
[fluentd-elasticsearch] logs weird warnings 

### ISSUE THREAD

**Issue by medmedchiheb** [kiwigrid/helm-charts#370]
**Is this a request for help?**:
Yes
---

**BUG REPORT** 

**Version of Helm and Kubernetes**:
Helm: v3.1.2
k8s: v1.16.9

**Which chart in which version**:
fluentd-elasticsearch

**What happened**:
Got those warnings, and stuck in Running state without working!

```
/usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:61: warning: The called method `initialize_client' is defined here
/usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/http_server/compat/server.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/fluentd-1.9.3/lib/fluent/plugin_helper/http_server/compat/webrick_handler.rb:26: warning: The called method `build' is defined here
```

**What you expected to happen**:
fleuntd work as expected 

**How to reproduce it** (as minimally and precisely as possible):
using default configmaps

**Anything else we need to know**:

**Comment by BertelBB** [comment]
Why was this closed? Did you find a solution?
I am getting the last two logs as well and fluentd-elasticsearch pods are restarting like crazy. Not sure if it's related.

**Comment by Kub4w** [comment]
> Why was this closed? Did you find a solution?
> I am getting the last two logs as well and fluentd-elasticsearch pods are restarting like crazy. Not sure if it's related.

Same issues here, did anyone find solution for this yet?
