### ISSUE TITLE
[fluentd-elasticsearch] change logstash_dateformat to a weekly format

### ISSUE THREAD

**Issue by rgarcia89** [kiwigrid/helm-charts#373]
I would like to switch from daily to weekly indexes.
Therefore I tried to pass the env variable `logstash_dateformat`

For testing I first tried the following
```
env:
  LOGSTASH_DATEFORMAT: "%Y"
```

I can see the env being set. However, the index still is getting yyyy.mm.dd as suffix.
According to https://www.rubydoc.info/gems/fluent-plugin-elasticsearch/1.5.0#logstash_dateformat this variable should bring the change. Am I missing something?

I am happy to create a pull request so that this variable can be set via the values file, once we have figured out, why it is not working.

Thanks in advance

**Comment by rgarcia89** [comment]
I have figured out the reason and created a pull request 
https://github.com/kiwigrid/helm-charts/pull/374

Looking forward to get merged
Thanks

**Comment by rgarcia89** [comment]
New pull request:
https://github.com/kiwigrid/helm-charts/pull/375

**Comment by monotek** [comment]
merged...
