### ISSUE TITLE
[fluentd-elasticsearch] Fluentd prints continuous deprecation warning against ES 7.3: "[types removal] Specifying types in bulk requests is deprecated."

### ISSUE THREAD

**Issue by Ghazgkull** [kiwigrid/helm-charts#381]
**Is this a request for help?**:
No.

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
```
$ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-eks-e16311", GitCommit:"e163110a04dcb2f39c3325af96d019b4925419eb", GitTreeState:"clean", BuildDate:"2020-03-27T22:37:12Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Which chart in which version**:
3.0.2

**What happened**:
When this helm chart is configured to point at Elasticsearch 7.3.2, the fluentd pods prints out the following message approximately once per second:
```
warning: 299 Elasticsearch-7.3.2-1c1faf1 "[types removal] Specifying types in bulk requests is deprecated."
```

**What you expected to happen**:
The pod should not continuously print out this warning.

**How to reproduce it** (as minimally and precisely as possible):
Deploy this helm chart pointing at an ES 7.3.2 domain.

**Anything else we need to know**:
The Elasticsearch plugin this chart uses is aware of this issue and has a flag which is supposed to stop the warnings: https://github.com/uken/fluent-plugin-elasticsearch#suppress_type_name

This flag should probably be added to this chart as a recommended option for people running against ES 7.x.

**Comment by Ghazgkull** [comment]
Note that the `suppress_type_name` flag was only recently added to fluent-plugin-elasticsearch and the fluentd-es-image Gemfile will need to be updated to a newer version in order for this Helm chart to get the support. I'll PR a change to that file momentarily (https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image/Gemfile).

**Comment by Ghazgkull** [comment]
@monotek Once the two PRs I have open against the fluent-es-image are merged, I'll volunteer to submit a PR here to expose the `suppress_type_name` flag in this chart as `elasticsearch.suppress_type_name`.

**Comment by monotek** [comment]
Many thanks. PR welcome :)

**Comment by Ghazgkull** [comment]
PR submitted. We'll have to wait until the k8s PR is merged and the new fluentd-elasticsearch image (v3.0.4) is available before the change to the chart can be merged.
