### ISSUE TITLE
[fluentd-elasticsearch] FEATURE: support for deployment instead of daemonset?

### ISSUE THREAD

**Issue by KlavsKlavsen** [kiwigrid/helm-charts#393]
Would you accept a PR for installing fluentd as deployment? (so I don't have a pod per physical node) - since I already have fluent-bit on all my nodes, and the configuration here even defaults to accept logs from fluent-bit forwarder.. In which case it does not make sense to run it as a daemonset ?

**Comment by monotek** [comment]
Thanks, but no.
I don't see this chart as a multi purpose chart.
It should do one thing and thats collecting node logs and send them to elasticsearch.
You might want to try https://github.com/helm/charts/tree/master/stable/fluentd/templates instead.
