### ISSUE TITLE
Fluentd elasticsearch - bulk request deprecated warning

### ISSUE THREAD

**Issue by oed-mertenss** [kiwigrid/helm-charts#395]
**Is this a request for help?**: Yes. Please fix this issue :)

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Version of Helm and Kubernetes**:
not of interest

**Which chart in which version**:
v7.9.0 - https://github.com/elastic/helm-charts/tree/master/elasticsearch
v3.0.4 - https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch

**What happened**:
Version incompatible 

**What you expected to happen**:
no bloating logs

**How to reproduce it** (as minimally and precisely as possible):
just start both and connect it together

**Anything else we need to know**:
nope

It would be awesome if someone could help :) Thanks in advance!

**Comment by bakkerpeter** [comment]
I believe this is the actual error @oed-mertenss is referring to:
```
warning: 299 Elasticsearch-7.8.1-x "[types removal] Specifying types in bulk requests is deprecated."
```
If this is the error that is being referred, I think the subject of this issue is unspecific as there is no issue with bulk requests in general.

**Comment by bakkerpeter** [comment]
Ok, this is solved by adding this config parameter (as described in https://github.com/kiwigrid/helm-charts/pull/384):
```
elasticsearch.suppressTypeName: true
```
