### ISSUE TITLE
Helm chart failing with error validating "": error validating data: [unknown object type "nil" in Secret.data.gitPassword, unknown object type "nil" in Secret.data.gitUsername]

### ISSUE THREAD

**Issue by Anurag-30** [kiwigrid/helm-charts#399]
**BUG REPORT**:

**Version of Helm and Kubernetes**:

Helm-Version: "v3.2.4"
Kubernetes: "v1.17.0"

**Which chart in which version**:
 
spring-cloud-config-server helm chart is failing when tried to install it using helm3

**What happened**:
 When I try to install the helm chart with the following command **helm install spring-cloud-config-server kiwigrid/spring-cloud-config-server** it throws the error.

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [unknown object type "nil" in Secret.data.gitPassword, unknown object type "nil" in Secret.data.gitUsername]

**What you expected to happen**:
If git username and password are mandatory please do update the readme accordingly. I see the default values for them are null, either this should be handled or should be made mandatory fields

**How to reproduce it** (as minimally and precisely as possible):
I just followed the instructions mentioned in hub.helm  --> https://hub.helm.sh/charts/kiwigrid/spring-cloud-config-server

helm repo add kiwigrid https://kiwigrid.github.io

helm install kiwigrid/spring-cloud-config-server --version 0.1.0

**Comment by Anurag-30** [comment]
we can use b64enc function to encrypt the plain text to base64. update the lines in secret.yaml to this:

data:
  gitUsername: {{ .Values.secrets.gitUsername | b64enc }}
  gitPassword: {{ .Values.secrets.gitPassword | b64enc }}

Update the readme with the same information.

**Comment by monotek** [comment]
Would you mind to add a PR for this please?

**Comment by Anurag-30** [comment]
I actually tried to raise one, It threw me a 403 when I tried to create a new branch and push the code.
