### ISSUE TITLE
liveness probe and readiness probe failing when passing the private git repository

### ISSUE THREAD

**Issue by Anurag-30** [kiwigrid/helm-charts#400]
**Is this a request for help?**:

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 BUG REPORT

**Version of Helm and Kubernetes**:
kubernetes: v1.17.0
helm: v3.2.4

**Which chart in which version**:

 kiwigrid/spring-cloud-config-server --version 0.1.0

**What happened**:

Liveness and readiness probes get failed when giving private git repositories. Here is the output when I do a describe of the pod.

 ```
Type     Reason     Age        From               Message
  ----     ------     ----       ----               -------
  Normal   Scheduled  <unknown>  default-scheduler  Successfully assigned apps/spring-config-spring-cloud-config-server-75c5b456ff-m7dh7 to minikube
  Normal   Pulled     17s        kubelet, minikube  Container image "hyness/spring-cloud-config-server:2.1.3.RELEASE" already present on machine
  Normal   Created    17s        kubelet, minikube  Created container spring-cloud-config-server
  Normal   Started    17s        kubelet, minikube  Started container spring-cloud-config-server
  Warning  Unhealthy  16s        kubelet, minikube  Readiness probe failed: Get http://172.17.0.4:8888/actuator/health: dial tcp 172.17.0.4:8888: connect: connection refused
  Warning  Unhealthy  6s         kubelet, minikube  Liveness probe failed: Get http://172.17.0.4:8888/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  5s         kubelet, minikube  Readiness probe failed: Get http://172.17.0.4:8888/actuator/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**What you expected to happen**:

The pod has to come up with out any errors.

**How to reproduce it** (as minimally and precisely as possible):

helm install spring-config kiwigrid/spring-cloud-config-server  --set config.gitUri=<private git repo> --set secrets.gitUsername=<base64 encode> --set secrets.gitPassword=<base64 encode> --set service.type=NodePort  

**Anything else we need to know**:
I did an helm fetch of the same chart and removed liveness and readiness probes , it started working as expected after doing so.

**Comment by monotek** [comment]
Fix in: https://github.com/kiwigrid/helm-charts/pull/401
