### ISSUE TITLE
[fluentd-elasticsearch] Add possibilty to inject self-managed side-cars

### ISSUE THREAD

**Issue by Alien2150** [kiwigrid/helm-charts#404]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Version of Helm and Kubernetes**:

Helm 2/3

**Which chart in which version**:
fluentd-elasticsearch, 9.6.1

**What happened**:
It would be helpful to add a possibility to inject self-managed sidecar containers (e.g fluentd-ui) into the daemonset. At the moment there is only 1 fixed sidecar container (es-proxy).

**Comment by monotek** [comment]
Chart was deprecated and moved to: https://github.com/kokuwaio/helm-charts/tree/main/charts/fluentd-elasticsearch
