### ISSUE TITLE
Trouble upgrading an existing release of fluentd-elasticsearch

### ISSUE THREAD

**Issue by rendhalver** [kiwigrid/helm-charts#42]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:

Helm 2.12
K8s: 1.12.3

**Which chart**:

fluentd-elasticsearch

**What happened**:

We have a release of fluentd-elasticsearch from the helm/charts repository with version 1.0.3
I am trying to upgrade that to 2.3.0 from this repository.

We use helmfile to do the deploying of our helm releases.

This was the output I got when trying to run helmfile sync.
```
09:47 $ CONTEXT="APP-Dev" helmfile --kube-context=kubernetes-admin-dev --file=HelmfileBootstrap.yaml --selector name=logging-fluentd sync
Adding repo stable https://kubernetes-charts.storage.googleapis.com
"stable" has been added to your repositories

Adding repo incubator https://kubernetes-charts-incubator.storage.googleapis.com
"incubator" has been added to your repositories

Adding repo elastic https://helm.elastic.co
"elastic" has been added to your repositories

Adding repo kiwigrid https://kiwigrid.github.io
"kiwigrid" has been added to your repositories

Adding repo stable_f5 https://f5networks.github.io/charts/stable
"stable_f5" has been added to your repositories

Updating repo
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "stable_f5" chart repository
...Successfully got an update from the "kiwigrid" chart repository
...Successfully got an update from the "elastic" chart repository
...Successfully got an update from the "incubator" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

Upgrading kiwigrid/fluentd-elasticsearch
Error: UPGRADE FAILED: DaemonSet.apps "logging-fluentd-fluentd-elasticsearch" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/name":"fluentd-elasticsearch", "app.kubernetes.io/instance":"logging-fluentd"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

err: release "logging-fluentd" in "HelmfileBootstrap.yaml" failed: exit status 1
exit status 1
```

If I try the upgrade with helm directly I get the same errors.
```
10:19 $ helm upgrade --install --debug --namespace=logging --kube-context=kubernetes-admin-dev logging-fluentd ./charts/fluentd-elasticsearch -f helmfile-values/logging-fluentd-elasticsearch.yaml
[debug] Created tunnel using local port: '54922'

[debug] SERVER: "127.0.0.1:54922"

Error: UPGRADE FAILED: DaemonSet.apps "logging-fluentd-fluentd-elasticsearch" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"logging-fluentd", "app.kubernetes.io/name":"fluentd-elasticsearch"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
**What you expected to happen**:

I expected the release to be upgraded to to new version.

**How to reproduce it** (as minimally and precisely as possible):

Install fluentd-elasticsearch 1.0.3 from helm/charts and upgrade it to fluentd-elasticsearch 2.3.0 from this repository.

**Anything else we need to know**:

**Comment by rendhalver** [comment]
I get the same error if I try upgrading from 1.5.0 to 2.0.0 in helm/charts.
2.0.0 was the switch to apps/v1 and it removes the old labels which a current release will use.
helm/charts#9382

So short version is it is impossible to upgrade from any version up to 1.5.0 to any version equal to or greater than 2.0.0.

**Comment by monotek** [comment]
Imho ok, as a major version bump can introduce braking changes.

Adding "--force" to helm upgrade should solve the problem. 

Maybe we should add an upgrading section to the readme...

**Comment by rendhalver** [comment]
True it is a major version increase.
Setting force did help.

**Comment by monotek** [comment]
Added upgrade note to readme in https://github.com/kiwigrid/helm-charts/commit/ed9c661128998c727a890fe9d56f16d2ac8f92f3#diff-17334a6940fa7ce172c171286835924a
