### ISSUE TITLE
gcp-serviceaccount-controller CRD validation error: unknown field "validation" and unknown field "version"

### ISSUE THREAD

**Issue by nicolasbelanger** [kiwigrid/helm-charts#422]
**Is this a request for help?**: yes, please.  can't deploy the newest version 0.2.6

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Version of Helm and Kubernetes**: helm 3.5.1 k8s 1.17.14

**Which chart in which version**: gcp-serviceaccount-controller 0.2.6

**What happened**: rendering the template does work, but error on helm diff: 
`Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): missing required field "versions" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]`

**What you expected to happen**: no error?! :) 0.2.5 does work correctly...

**How to reproduce it** (as minimally and precisely as possible): 
`
helm diff upgrade gcp-serviceaccount-controller kiwigrid/gcp-serviceaccount-controller --allow-unreleased --suppress-secrets --version 0.2.6 --namespace infra
`

**Anything else we need to know**:

**Comment by rpahli** [comment]
I'll have a look

**Comment by rpahli** [comment]
@nicolasbelanger can you pls retry it with version 0.3.0

**Comment by nicolasbelanger** [comment]
@rpahli Thanks for the quick release.  Unfortunately, there are still issues with `0.3.0`... 

`Error: Failed to render chart: exit status 1: Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec, ValidationError(CustomResourceDefinition.spec): unknown field "version" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec]`

So `missing required field "versions"` is fixed, but still erroring on `unknown field "validation"` + `unknown field "version"`...

**Comment by rpahli** [comment]
Ok I was a little bit to greedy with chanching the version to v1. Now it should work with `0.3.1`.

**Comment by nicolasbelanger** [comment]
Yeah, now the diff passes 👍  Will try to deploy and test it soon.  Thanks!
