### ISSUE TITLE
gcp-serviceaccount-controller - unable to find api field in struct CustomResourceDefinitionSpec for the json field "validation"

### ISSUE THREAD

**Issue by nicolasbelanger** [kiwigrid/helm-charts#438]
**Is this a request for help?**: Yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Version of Helm and Kubernetes**: helm 3.5.1 kubernetes 1.20.8

**Which chart in which version**: 0.3.1

**What happened**: failed to create patch: unable to find api field in struct CustomResourceDefinitionSpec for the json field "validation" && failed to create patch: unable to find api field in struct CustomResourceDefinitionSpec for the json field "validation"

**What you expected to happen**: No error

**How to reproduce it** (as minimally and precisely as possible): helm upgrade from 0.2.5

**Anything else we need to know**: - This was my first attempt to install since https://github.com/kiwigrid/helm-charts/issues/422 fix.

**Comment by rpahli** [comment]
I'll try to have a look next week.

**Comment by rpahli** [comment]
ok I tested the update from 0.2.5 -> 0.3.1 I found 1 issue but it was not related to the crd it was only related to the statefulset. I fixed it with version 0.3.2. 

I used k8s in version 1.21.4
