### ISSUE TITLE
Empty message after deploy

### ISSUE THREAD

**Issue by pimjansen** [kiwigrid/helm-charts#51]
**Version of Helm and Kubernetes**:
Helm: 2.13.0
K8s: v1.10.0

**Which chart in which version**:
fluentd-elasticsearch-2.5.0

**What happened**:
Installed  helm chart and all is running fine. However in ES empty log messages are appearing. This is the way we are logging with Log4J:
`<Property name="CONSOLE_LOG_PATTERN">%d{ISO8601} [%thread] %highlight{%-5level} %logger{36}.%M: %m%ex%throwable{none}%n</Property>`

> March 6th 2019, 09:40:24.601 | checkout-api | 2019-03-06T08:39:55,180 [main] [1;31mERROR[m org.springframework.boot.SpringApplication.reportFailure: Application startup failed org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat 
> March 6th 2019, 09:40:24.601 | checkout-api

**What you expected to happen**:
I expect it to recognize multilines properly. Since there are no newlines in the console logs itself i also do not expect them in ES itself

**How to reproduce it** (as minimally and precisely as possible):
Hard for me to say since its just a default install of the package. Maybe by using the logformat we use?

**Anything else we need to know**:
N/A

**Comment by monotek** [comment]
I'have seen this for other Java stacktraces before.
Multiline logging for such errors can't be guaranteed. 
You should try to log in JSON format, which fixed the problem for us.

**Comment by pimjansen** [comment]
@monotek i tried but it does not seem to solve the issue. So for Log4J i send to JSON format:

```
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT" follow="true">
            <JsonLayout complete="false" compact="false" />
        </Console>
```
After this i receive indeed proper json formatted logs. Only after that in Kibana it shows up like:

> message |   | }
> stream |   | stdout
> tag |   | kubernetes.var.log.containers.checkout-api-fbd475b5c-dr6rq_api-720fdd75ae31d1a568473cd1798f83920be2e44e3771e93e4e80af047724933b.log

So it seems it tries not to parse them as expected here and every line of the json object is parsed literly. I also see the indents before the "message" field back in kibana is whitespace even though it should be the key itself

**Comment by monotek** [comment]
At the moment my only source of JSON logs is Kibana 6.6.0, and there it works as expected. 
All JSON fields are converted to Elasticsearch fields.
