### ISSUE TITLE
fluentd-elasticsearch plugins 

### ISSUE THREAD

**Issue by cpanato** [kiwigrid/helm-charts#54]
is it possible to install plugins in the fluentd? if yes how can I setup?

thanks so much!

**Comment by monotek** [comment]
You could use another docker image witch have the plugins installed.
Installing via the helm chart is not possible.

**Comment by cpanato** [comment]
thanks!!

**Comment by monotek** [comment]
Which plugin do need by the way and why?

**Comment by cpanato** [comment]
the slack one, i would like to post some messages

**Comment by zepekenio** [comment]
Hi Guys,
Thank you for this work!  
Is it possible to add some plugins in the future? Like the geo-ip plugin. Thanks !

**Comment by monotek** [comment]
We're using the "official" Kubernetes fluentd-elasticsearch image from gcr.io/google-containers/fluentd-elasticsearch (which will move to gcr.io/fluentd-elasticsearch soon).

As alread discussed in https://github.com/kubernetes/kubernetes/pull/74517#issuecomment-467825397 we don't like to add stuff there which is not used by everyone.

Just use the image as a base for your changes and build your own. The Dockerfile of the image can be forund here: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
