### ISSUE TITLE
SSL_VERIFY??

### ISSUE THREAD

**Issue by polinchw** [kiwigrid/helm-charts#58]
Is there a way to set ssl_verify=false when installing this chart?   I have a ES server with a self signed cert that I want to send traffic to.  If I set the scheme=https and port=443 I get an SSL verification error back from Fluentd.  

This is a question for the fluentd-elasticsearch chart.

**Comment by monotek** [comment]
https://github.com/uken/fluent-plugin-elasticsearch/#user-password-path-scheme-ssl_verify

**Comment by polinchw** [comment]
I fixed it with the following:
Fixed with changes to the elasticsearch plugin in values.yaml. I had to add ssl_version and ssl_verify settings:

<match **> 
@id elasticsearch 
@type elasticsearch 
@log_level info 
include_tag_key true 
type_name fluentd 
ssl_verify false 
scheme https
" ssl_version SSLv23

**Comment by monotek** [comment]
added the option to the config: https://github.com/kiwigrid/helm-charts/pull/61
