### ISSUE TITLE
Kube 1.11 install error

### ISSUE THREAD

**Issue by ceastman-ibm** [kiwigrid/helm-charts#68]
**Is this a request for help?**: yes

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Version of Helm and Kubernetes**:
helm version 2.9.1
Kubernetes master version 1.11.8_1552
Kubernetes workers version 1.11.8_1547

**Which chart in which version**:
graphite chart
image:
  repository: graphiteapp/graphite-statsd
  tag: 1.1.5-10

**What happened**:
The pod/container fails to create: CreateContainerError

in the kube logs: kubectl describe pod graphite-0

(combined from similar events): Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/922cfa93053db8e428823b201b481143f9cc230f18ff42b9f37fa77161db1b9f/volumes/bd1403ba9f315e8c02c1add7951089dda95a42c6e1d86893593749738fa8ed51: no such file or directory

**What you expected to happen**:
the pod to be created

**How to reproduce it** (as minimally and precisely as possible):
helm repo add kiwigrid https://kiwigrid.github.io
helm install kiwigrid/graphite --name graphite

**Anything else we need to know**:
This is on IBM's kubernetes infrastructure

**Comment by ceastman-ibm** [comment]
Update - I created a new cluster with Kube 1.10 and with the same helm chart was able to successfully install. So it looks like an issue with kube 1.11+ ?

**Comment by ceastman-ibm** [comment]
I upgraded that cluster to kube 1.12 and now getting a container create error.

**Comment by monotek** [comment]
Works for me on gke 1.11.6.
We can't test on IBM cloud.

**Comment by ceastman-ibm** [comment]
@monotek i have an ibm cloud cluster, what testing can i do for you?

**Comment by monotek** [comment]
Whats the output of: 

kubectl describe pod zammad-0

**Comment by ceastman-ibm** [comment]
kubectl describe pod graphite-0
Name:		graphite-0
Namespace:	influxdb
Node:		10.176.72.116/10.176.72.116
Start Time:	Wed, 03 Apr 2019 11:49:09 -0500
Labels:		app.kubernetes.io/instance=graphite
		app.kubernetes.io/name=graphite
		controller-revision-hash=graphite-6d4dfcbfdb
		statefulset.kubernetes.io/pod-name=graphite-0
Annotations:	kubernetes.io/psp=ibm-privileged-psp
Status:		Pending
IP:		172.30.216.67
Controllers:	<none>
Containers:
  graphite:
    Container ID:	
    Image:		graphiteapp/graphite-statsd:1.1.5-4
    Image ID:		
    Ports:		8080/TCP, 2003/TCP, 2004/TCP, 2023/TCP, 2024/TCP, 8125/UDP, 8126/TCP
    State:		Waiting
      Reason:		CreateContainerError
    Ready:		False
    Restart Count:	0
    Liveness:		http-get http://:graphite-gui/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:		http-get http://:graphite-gui/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      STATSD_INTERFACE:	udp
    Mounts:
      /opt/graphite/conf/ from graphite-configmap (rw)
      /opt/graphite/storage/ from graphite-pvc (rw)
      /opt/statsd/config_tcp.js from graphite-statsd-configmap (rw)
      /opt/statsd/config_udp.js from graphite-statsd-configmap (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t7lpd (ro)
Conditions:
  Type			Status
  Initialized 		True 
  Ready 		False 
  ContainersReady 	False 
  PodScheduled 		True 
Volumes:
  graphite-configmap:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	graphite-configmap
    Optional:	false
  graphite-statsd-configmap:
    Type:	ConfigMap (a volume populated by a ConfigMap)
    Name:	graphite-statsd-configmap
    Optional:	false
  graphite-pvc:
    Type:	PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:	graphite-pvc
    ReadOnly:	false
  default-token-t7lpd:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-t7lpd
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	node.kubernetes.io/not-ready=:Exists:NoExecute for 300s
		node.kubernetes.io/unreachable=:Exists:NoExecute for 300s
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason			Message
  ---------	--------	-----	----			-------------			--------	------			-------
  6m		6m		1	default-scheduler					Normal		Scheduled		Successfully assigned influxdb/graphite-0 to 10.176.72.116
  11m		6m		12	default-scheduler					Warning		FailedScheduling	pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Normal		Pulling			pulling image "graphiteapp/graphite-statsd:1.1.5-4"
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/caa688b49dfcb811e0d1a9e5c91543775307ace5ab79f73f02e8c3b999a53dc4/volumes/2895467dc7a0ed091ffc9660663741267d4397be1fd94e9086777bf2965a2a07: no such file or directory
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Normal		Pulled			Successfully pulled image "graphiteapp/graphite-statsd:1.1.5-4"
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/f8d8fe64d1f8ef8dc07675932336d78c97185860d4c942e35488ac2f649774e8/volumes/2157e6a89f5d7edc167b464ec361a9fada12da6839591f66bdb61e21b2bb41b9: no such file or directory
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/a44fce5972bea10d89ce21f15beb7f13469fd4b34624caa7bfb42776286b6f70/volumes/db843d44f615daa4086843e6a046279a9cddab270c37fc05e7c922210adbc78c: no such file or directory
  6m		6m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/9746eaf16c0db2a8753d4ee3555913c6b1b30e78931fab8488ae2ae97395cb8a/volumes/847c4700b71f35b22ee0b3638269ca34434b84b97d9b022784d759ff9f489450: no such file or directory
  5m		5m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/880d90745a78e92a00e66bdfc26c102fcc0c253e9850dec45ee8251d346ab7b4/volumes/77caebc4d39be926c6ae874c74f18a76ca7012aec681591d01776df346f4025a: no such file or directory
  5m		5m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/7b6250db907199756ae7373618ba408ee8d91550acc1dfffd385ce3f50a4f245/volumes/df4bcb489d811903490ddc4047517316cadd97900461dd69dbe98ea4b9f4273d: no such file or directory
  5m		5m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/4bdc898bd3dbf4340e17ec175cf2f871acb0e9e133bce7521b7d1b4c4aea909b/volumes/bd49f9bbd6274a90e7e777dfa6ed9c2dc5d40e984ae242fa9cfe2f690b8b54cc: no such file or directory
  5m		5m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/795b4eb48b536f27395a3ed58f9cb7e36d5a6a125b168fa638dbb82d82c53293/volumes/7c963ff53327afb7d47351918c6b3b50619cf89b9ec8ee26feb07e1a61a0d60e: no such file or directory
  4m		4m		1	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/7607957e82f1ea52c8670dd5b3b6f141a784db9971be63d66c4760647298d2d0/volumes/50848a4de0eac8ccf5c92111de4a1ecc3943bb7b571ffc2e337e50ae73b96d00: no such file or directory
  4m		4m		3	kubelet, 10.176.72.116	spec.containers{graphite}	Warning		Failed			(combined from similar events): Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/e5c05c174291f467f37e91bfc6a26fc2555447a12a5352c0ff301bb8d0de2136/volumes/d3b19a1fc17e2f00f5851fd90ea96d96e079b043032e7bdb921977afcc27b0e9: no such file or directory
  6m		1m		23	kubelet, 10.176.72.116	spec.containers{graphite}	Normal		Pulled			Container image "graphiteapp/graphite-statsd:1.1.5-4" already present on machine

**Comment by monotek** [comment]
For me this looks like a problem with your Kubernetes installation, not with our Helm chart.

```Warning	FailedScheduling	pod has unbound immediate PersistentVolumeClaims (repeated 3 times)```

```Warning	Failed	Error: failed to create containerd container: taking runtime copy of volume: open /var/data/cripersistentstorage/io.containerd.grpc.v1.cri/containers/caa688b49dfcb811e0d1a9e5c91543775307ace5ab79f73f02e8c3b999a53dc4/volumes/2895467dc7a0ed091ffc9660663741267d4397be1fd94e9086777bf2965a2a07: no such file or directory```

**Comment by monotek** [comment]
No feedback. Closing...
