### ISSUE TITLE
Request for interest

### ISSUE THREAD

**Issue by SandyChapman** [kiwigrid/helm-charts#81]
Hey,

I've recently been using the `fluentd-elasticsearch` chart (thanks for it). We are currently using fluentd in our Amazon EKS cluster. We set up an AWS ES Domain, however, this requires all requests to ES to be signed using Amazon's IAM v4 signature format.

I've modified the fluentd-elasticsearch chart to add support for including a proxy sidecar that signs the requests coming from fluentd before sending them off to AWS ES. This is enabled with a templated flag.

Proxy project: https://github.com/abutaha/aws-es-proxy

Is there any interest in merging this change into the chart? I can prepare and open a PR for review if desired.

Cheers,
Sandy

**Comment by monotek** [comment]
Sure, as long as it's optional 😀

**Comment by SandyChapman** [comment]
PR opened in https://github.com/kiwigrid/helm-charts/pull/82
