### ISSUE TITLE
Detected ES 7.x or above: `_doc` will be used as the document `_type`.

### ISSUE THREAD

**Issue by innovia** [kiwigrid/helm-charts#86]
**Is this a request for help?**:
yes
---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Version of Helm and Kubernetes**:
kubernetes 1.11.5
helm 2.9.1

**Which chart in which version**:  2.9.0

**What happened**:
i keep getting this message which kills my cluster

```
fluentd-elasticsearch-b5rk9 fluentd-elasticsearch 2019-05-05 12:43:00 +0000 [warn]: [elasticsearch] Detected ES 7.x or above: `_doc` will be used as the document `_type`.```

**What you expected to happen**:
value.yaml specifies output settings with 
`type_name _doc`
but it's not applied?

**How to reproduce it** (as minimally and precisely as possible):
open an account on elasitc cloud and set the output to it

**Anything else we need to know**:

**Comment by monotek** [comment]
This is just a Warning.
I doubt that this has anything to do with an unavailable cluster.

**Comment by innovia** [comment]
it seems like fluentd current version is not compatible with ES7

I've switched to filebeat and everything is a smooth sailing now

**Comment by monotek** [comment]
I guess you ran into: https://github.com/kiwigrid/helm-charts/pull/88
