### ISSUE TITLE
help on configuring elasticsearch with fluentd

### ISSUE THREAD

**Issue by obeyler** [kiwigrid/helm-charts#95]
**Is this a request for help?**: yes

Inside the value.yaml I see that to works with elasticsearch we need to install also the fluentd-elasticsearch plugin 
---

>     # These logs are then submitted to Elasticsearch which assumes the
>     # installation of the fluent-plugin-elasticsearch & the
>     # fluent-plugin-kubernetes_metadata_filter plugins.
>     # See https://github.com/uken/fluent-plugin-elasticsearch &
>     # https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter for
>     # more information about the plugins.
I don't find the right way to install the plugin you've mention with the helm chart of stable/elasticsearch 
Have you got an example of how to do ? 
Thanks by advance

**Comment by monotek** [comment]
The plugin is already installed inside the fluentd-elasticsearch container which is used by the helm chart.

**Comment by obeyler** [comment]
Thanks for your answer !
I've got another question : everything seems to be well installed but each 8 daemons  have the same kind of log for all of installed charts  every are excluded and would be examined next time
so nothing arrive on the elasticsearch

>  2019-05-11 21:39:03 +0000 [warn]: [fluentd-containers.log] /var/log/containers/apprepo-sync-kiwigrid-2dnrk-6n7tz_kubeapps_sync-31c0a131158626a99cd571db65246e7074d966916ebc43fd6c68182b8411c655.log unreadable. It is excluded and would be examined next time.
2019-05-11 21:39:03 +0000 [warn]: [fluentd-containers.log] /var/log/containers/apprepo-sync-stable-p52f2-h6sjl_kubeapps_sync-dad055977ec9b4ad919ba6e81b12f10a49d66ad57af8f261a9ae4464f55ec3e9.log unreadable. It is excluded and would be examined next time. 

.

**Comment by obeyler** [comment]
I add a new feature request for this previous question
https://github.com/kiwigrid/helm-charts/issues/96
